#
services:
  rustup:
    image: dockerapp/rustup
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - HOSTOS=darwin
        - HOSTARCH=arm64
        # - HOSTOS=linux
        # - HOSTARCH=amd64